# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /TigerSweet/images/logo.svg

# Theme Main Subtitle
subtitle_main: Tiger Sweet 

# Theme Secondary subtitle
susbtitle_secondary: Chinese homemade Bakery

# Footer About Section
about_footer: Tiger Sweet -Chinese homemade Bakery

# Default post title
default_post_title: New Dessert

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates: 

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  # disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid: 956418721146800
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-82815285-1
favicon: images/favicon.ico
# Social Accounts
facebook_url: https://www.facebook.com/tigersweetscolumbia
#twitter_url: https://twitter.com/?lang=en
#instagram_url: https://www.instagram.com/
#dribble_url: https://dribbble.com/
#github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
#googleplus_url: https://plus.google.com/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
#email_url: \#
#rss_url: \#
#